name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  frontend:
    name: Frontend CI/CD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: ./cantao_frontend
        run: npm install

      - name: Run Jest tests
        working-directory: ./cantao_frontend
        run: npm test

      - name: Build project
        working-directory: ./cantao_frontend
        run: npm run build

  backend:
    name: Backend CI/CD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        working-directory: ./cantao_backend
        run: npm install

      - name: Run tests
        working-directory: ./cantao_backend
        run: npm test
